name: 'dbt_coord_postcode_data'
version: '1.0.0'
config-version: 2
profile: 'dbt-postgres'
model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
docs-paths: ['docs']
asset-paths: ['assets']
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_modules'
  - 'logs'
